#!/usr/bin/env python3
"""Install the Claude Code proxy wrapper for your shell.

What this does:
    Detects your OS and shell, then adds a `claude` function to your
    shell rc file. The function:

      1. Checks if the proxy is already running on localhost:9999
      2. If not, starts it lazily in the background (hidden)
      3. Sets ANTHROPIC_BASE_URL=http://localhost:9999 for this child
      4. Sets CLAUDE_CODE_BLOCKING_LIMIT_OVERRIDE=9000000 to disable
         Claude Code's client-side context-limit check so the proxy
         (not the client) decides whether a request is too big.
         See docs/claude-proxy-design.md for why this is needed.
      5. Calls the REAL claude binary, passing through your args

    After install, just type `claude` as usual. The proxy is invisible.

Usage:
    python install_claude_proxy.py            # install
    python install_claude_proxy.py --uninstall  # remove

Supports:
    - Windows / PowerShell (writes to $PROFILE)
    - macOS / bash + zsh
    - Linux / bash + zsh

The wrapper is delimited by markers so re-running the installer
overwrites the old version cleanly.
"""

from __future__ import annotations

import os
import platform
import shutil
import sys
from pathlib import Path


PROXY_PY = (Path(__file__).resolve().parent / "claude_proxy.py").as_posix()
PYTHON_BIN = sys.executable

WRAPPER_BEGIN = "# >>> claude_proxy wrapper >>>"
WRAPPER_END = "# <<< claude_proxy wrapper <<<"


# ---------- shell wrapper templates ----------

POSIX_WRAPPER = f"""{WRAPPER_BEGIN}
# Lazy-start claude_proxy and route `claude` through it.
# Generated by install_claude_proxy.py — re-run installer to update,
# or run `python install_claude_proxy.py --uninstall` to remove.
claude() {{
    # Check if proxy is already listening on 9999
    if ! (exec 3<>/dev/tcp/127.0.0.1/9999) 2>/dev/null; then
        # Not running — start it in the background, detached
        nohup "{PYTHON_BIN}" "{PROXY_PY}" >/dev/null 2>&1 &
        # Wait up to 2s for it to bind
        for _ in 1 2 3 4 5 6 7 8 9 10; do
            (exec 3<>/dev/tcp/127.0.0.1/9999) 2>/dev/null && exec 3<&- 3>&- && break
            sleep 0.2
        done
    else
        exec 3<&- 3>&-
    fi
    ANTHROPIC_BASE_URL="http://localhost:9999" \\
    CLAUDE_CODE_BLOCKING_LIMIT_OVERRIDE="9000000" \\
        command claude "$@"
}}
{WRAPPER_END}
"""

PWSH_WRAPPER = f"""{WRAPPER_BEGIN}
# Lazy-start claude_proxy and route `claude` through it.
# Generated by install_claude_proxy.py — re-run installer to update,
# or run `python install_claude_proxy.py --uninstall` to remove.
function claude {{
    $port = 9999
    function Test-ProxyUp {{
        try {{
            $tcp = New-Object System.Net.Sockets.TcpClient
            $tcp.Connect("127.0.0.1", $port)
            $tcp.Close()
            return $true
        }} catch {{
            return $false
        }}
    }}

    if (-not (Test-ProxyUp)) {{
        # Start proxy in the background, hidden window
        Start-Process -WindowStyle Hidden -FilePath "{PYTHON_BIN}" `
            -ArgumentList "{PROXY_PY}"
        # Wait up to 2s for it to bind
        for ($i = 0; $i -lt 20; $i++) {{
            if (Test-ProxyUp) {{ break }}
            Start-Sleep -Milliseconds 100
        }}
    }}

    $env:ANTHROPIC_BASE_URL = "http://localhost:$port"
    $env:CLAUDE_CODE_BLOCKING_LIMIT_OVERRIDE = "9000000"

    # Call the real claude binary, bypassing this function
    $real = Get-Command claude -CommandType Application -ErrorAction SilentlyContinue |
            Select-Object -First 1
    if ($real) {{
        & $real.Source @args
    }} else {{
        Write-Error "claude binary not found in PATH. Install Claude Code first."
    }}
}}
{WRAPPER_END}
"""


# ---------- helpers ----------

def detect_os() -> str:
    s = platform.system()
    if s == "Windows":
        return "windows"
    if s == "Darwin":
        return "mac"
    if s == "Linux":
        return "linux"
    return s.lower()


def find_real_claude() -> str | None:
    return shutil.which("claude")


def get_posix_rc_files() -> list[Path]:
    """Return shell rc files we should install into. Picks bash + zsh."""
    home = Path.home()
    files: list[Path] = []

    # bash
    if (home / ".bashrc").exists():
        files.append(home / ".bashrc")
    elif platform.system() == "Darwin" and (home / ".bash_profile").exists():
        files.append(home / ".bash_profile")

    # zsh
    if (home / ".zshrc").exists():
        files.append(home / ".zshrc")

    # If neither exists, default to bashrc (will create it)
    if not files:
        files.append(home / ".bashrc")

    return files


def get_powershell_profiles() -> list[Path]:
    """Return all PowerShell profile paths (PS5 + PS7) that exist or
    that we want to install into. Both, so the wrapper works whether
    the user runs Windows PowerShell 5.x or PowerShell 7.x.
    """
    home = Path.home()
    ps5 = home / "Documents" / "WindowsPowerShell" / "Microsoft.PowerShell_profile.ps1"
    ps7 = home / "Documents" / "PowerShell" / "Microsoft.PowerShell_profile.ps1"
    return [ps5, ps7]


def strip_existing_wrapper(content: str) -> str:
    """Remove any existing wrapper block (between markers)."""
    if WRAPPER_BEGIN not in content:
        return content
    lines = content.splitlines(keepends=True)
    out: list[str] = []
    skip = False
    for line in lines:
        if WRAPPER_BEGIN in line:
            skip = True
            continue
        if WRAPPER_END in line:
            skip = False
            continue
        if not skip:
            out.append(line)
    # Trim trailing blank lines that might be left behind
    result = "".join(out).rstrip() + "\n"
    return result


def install_to_file(rc_path: Path, wrapper: str) -> None:
    rc_path.parent.mkdir(parents=True, exist_ok=True)
    if rc_path.exists():
        content = rc_path.read_text(encoding="utf-8")
        content = strip_existing_wrapper(content)
    else:
        content = ""
    if content and not content.endswith("\n"):
        content += "\n"
    content += "\n" + wrapper
    rc_path.write_text(content, encoding="utf-8")


def uninstall_from_file(rc_path: Path) -> bool:
    """Remove wrapper from rc file. Returns True if anything was removed."""
    if not rc_path.exists():
        return False
    content = rc_path.read_text(encoding="utf-8")
    if WRAPPER_BEGIN not in content:
        return False
    new_content = strip_existing_wrapper(content)
    rc_path.write_text(new_content, encoding="utf-8")
    return True


# ---------- main ----------

def preflight_check_deps() -> None:
    """Verify claude_proxy's runtime dependencies are importable before we
    touch the shell rc file. A half-installed wrapper that points at a
    proxy that can't start is worse than a clear upfront error.
    """
    missing: list[str] = []
    for mod in ("httpx", "fastapi", "uvicorn"):
        try:
            __import__(mod)
        except ImportError:
            missing.append(mod)
    if missing:
        req_path = Path(__file__).resolve().parent / "requirements.txt"
        print("ERROR: claude_proxy dependencies not installed in this Python:", file=sys.stderr)
        print(f"  missing: {', '.join(missing)}", file=sys.stderr)
        print(f"  python:  {PYTHON_BIN}", file=sys.stderr)
        print(file=sys.stderr)
        print("Fix:", file=sys.stderr)
        print(f'  "{PYTHON_BIN}" -m pip install -r "{req_path}"', file=sys.stderr)
        print(file=sys.stderr)
        print("Then re-run this installer.", file=sys.stderr)
        sys.exit(1)


def cmd_install() -> None:
    preflight_check_deps()

    os_name = detect_os()
    real_claude = find_real_claude()

    print(f"OS:           {os_name}")
    print(f"Python:       {PYTHON_BIN}")
    print(f"Proxy script: {PROXY_PY}")
    print(f"Real claude:  {real_claude or '(not found in PATH — install Claude Code)'}")
    print()

    if not Path(PROXY_PY).exists():
        print(f"ERROR: proxy script not found at {PROXY_PY}", file=sys.stderr)
        sys.exit(1)

    print("Installing wrapper...")

    if os_name == "windows":
        for profile in get_powershell_profiles():
            install_to_file(profile, PWSH_WRAPPER)
            print(f"  ✓ {profile}")
        print()
        print("Restart PowerShell (or open a new terminal) and just run:  claude")
    else:
        rc_files = get_posix_rc_files()
        for rc in rc_files:
            install_to_file(rc, POSIX_WRAPPER)
            print(f"  ✓ {rc}")
        print()
        print("Restart your shell (or `source` the rc file) and just run:  claude")

    print()
    print("To remove later:  python install_claude_proxy.py --uninstall")


def cmd_uninstall() -> None:
    os_name = detect_os()
    print("Removing claude_proxy wrapper...")

    if os_name == "windows":
        files = get_powershell_profiles()
    else:
        files = get_posix_rc_files()
        # Also check both bash variants on macOS
        home = Path.home()
        for extra in (home / ".bashrc", home / ".bash_profile", home / ".zshrc"):
            if extra not in files:
                files.append(extra)

    removed_any = False
    for rc in files:
        if uninstall_from_file(rc):
            print(f"  ✓ removed from {rc}")
            removed_any = True

    if not removed_any:
        print("  (nothing to remove)")
    print()
    print("Done. Restart your shell to take effect.")


def main() -> int:
    if "--uninstall" in sys.argv or "-u" in sys.argv:
        cmd_uninstall()
    elif "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__)
    else:
        cmd_install()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
