#!/usr/bin/env python3
"""Stop hook — if today's quiz hasn't been taken, block Claude and inject quiz instructions."""

import json
import sys
from pathlib import Path
from _shared import today_kst

SCRIPT_DIR = Path(__file__).resolve().parent
TAKEN_FILE = SCRIPT_DIR / 'quiz-last-taken.txt'
DISMISSED_FILE = SCRIPT_DIR / 'quiz-last-dismissed.txt'

# Read hook stdin to check stop_hook_active (prevents infinite loop)
try:
    hook_input = json.loads(sys.stdin.read())
except Exception:
    hook_input = {}

if hook_input.get('stop_hook_active'):
    raise SystemExit(0)

# Venv python path for commands in output instructions
if sys.platform == 'win32':
    VENV_PYTHON = str(SCRIPT_DIR / '.venv' / 'Scripts' / 'python.exe')
else:
    VENV_PYTHON = str(SCRIPT_DIR / '.venv' / 'bin' / 'python')

today = today_kst()

last_taken = ''
last_dismissed = ''
try:
    last_taken = TAKEN_FILE.read_text(encoding='utf-8').strip()
except FileNotFoundError:
    pass
try:
    last_dismissed = DISMISSED_FILE.read_text(encoding='utf-8').strip()
except FileNotFoundError:
    pass

if last_taken == today or last_dismissed == today:
    raise SystemExit(0)

# Local cache miss — check MongoDB (source of truth, shared across machines).
# Retry transient failures, then FAIL SILENT (do not block) on hard failure.
# Rationale: a missed nag is harmless, but false-nagging a quiz already taken
# or dismissed on another machine is the bug we're fixing. The local cache
# already covers the same-machine case, so silence here only affects the rare
# "fresh on this machine AND MongoDB unreachable" double-fault.
import sys as _sys

marker = None
graded = None
pending_quiz = None
mongo_ok = False
for attempt in range(2):
    try:
        from _shared import get_db_fast
        client, db = get_db_fast(timeout_ms=2500)
        marker = db['quiz-markers'].find_one({'date': today})
        # Belt-and-suspenders: a quiz can be GRADED (score written to daily-quizzes)
        # before / without the marker's taken_at landing — that lag was the false-nag
        # window. Treat any graded quiz for today as "taken" too, so we never nag
        # (or regenerate a new quiz) once one has actually been answered today.
        graded = db['daily-quizzes'].find_one({'date': today, 'score': {'$ne': None}})
        # One-quiz-per-day: an existing UNGRADED quiz for today (generated by another
        # session) is re-presented instead of generating a new one. Earliest-first so
        # every session/machine converges on the same quiz.
        pending_quiz = db['daily-quizzes'].find_one(
            {'date': today, 'score': None}, sort=[('created_at', 1)])
        client.close()
        mongo_ok = True
        break
    except Exception as e:
        print(f'[quiz_check] MongoDB check attempt {attempt + 1} failed: '
              f'{type(e).__name__}: {e}', file=_sys.stderr)

if mongo_ok:
    taken = bool(marker and marker.get('taken_at')) or bool(graded)
    dismissed = bool(marker and marker.get('dismissed_at'))
    if taken or dismissed:
        # Already taken/graded/dismissed today — cache locally so future fires skip MongoDB
        if taken:
            TAKEN_FILE.write_text(today, encoding='utf-8')
        if dismissed:
            DISMISSED_FILE.write_text(today, encoding='utf-8')
        raise SystemExit(0)
    # Reachable and confirms genuinely pending — fall through to show the quiz
else:
    # Unreachable after retries — stay silent rather than false-nag
    print('[quiz_check] MongoDB unreachable after retries; failing silent', file=_sys.stderr)
    raise SystemExit(0)

# One-quiz-per-day: if today's quiz already exists (another session generated it)
# but isn't graded yet, re-present THAT quiz instead of generating a new one, so
# concurrent sessions/machines share a single daily quiz.
if pending_quiz is not None:
    qid = str(pending_quiz.get('_id'))
    qlines = []
    for _i, _q in enumerate(pending_quiz.get('questions', []), 1):
        qlines.append(f"{_i}. {_q.get('q', '')}")
        qlines.append("   " + " · ".join(_q.get('choices', [])))
    questions_block = "\n".join(qlines)
    instructions = f"""[DAILY QUIZ] Today's quiz already exists (shared across your sessions) — present THIS existing quiz. Do NOT generate or save a new one.

quiz_id: {qid}

1. Present all questions below as a numbered list titled "## Daily Quiz - {today}", with choices in compact one-line format (A) ... · B) ... · C) ... · D) ...). Do NOT reveal answers.
2. Wait for the user's answers. When showing an example answer format, use a generic pattern like "A B C D A" — never build it from the real answers.
3. Grade by piping their answers as JSON to stdin:
   echo '{{"quiz_id": "{qid}", "answers": ["B", "C", "A", ...]}}' | {VENV_PYTHON} {SCRIPT_DIR}/quiz_grade.py
   The script returns score, total, and per-question results. Show the score; for EVERY wrong answer, render the question with all four choices verbatim, mark the user's pick and the correct pick, and explain why the correct one is right.

ONLY dismiss if the user EXPLICITLY says "skip quiz", "no quiz today", or "dismiss quiz":
   {VENV_PYTHON} {SCRIPT_DIR}/quiz_dismiss.py

Questions:
{questions_block}"""
    instructions_file = SCRIPT_DIR / 'quiz-instructions-active.txt'
    instructions_file.write_text(instructions, encoding='utf-8')
    reason = f"Daily quiz pending. Read {instructions_file} and follow the instructions."
    print(json.dumps({"decision": "block", "reason": reason}))
    raise SystemExit(0)

# No quiz exists for today yet — generate a fresh one.
# Write detailed instructions to a temp file for Claude to read
instructions = f"""[DAILY QUIZ] The user has not taken today's quiz yet.

IMPORTANT: Before doing ANY work the user asks for, you MUST run the daily quiz first.

Steps:
1. Launch a BACKGROUND agent to handle steps 2-4 below. Greet the user and tell them the quiz is being prepared while they can share what they want to work on.
2. (In background agent) Run: {VENV_PYTHON} {SCRIPT_DIR}/quiz_data.py
   This returns yesterday's conversation summaries from MongoDB.
3. (In background agent) Generate exactly 5 multiple-choice questions (4 choices each) based on that data.
   Focus on: concepts discussed, code patterns used, technical decisions made, bugs fixed.
4. (In background agent) IMMEDIATELY save the quiz to MongoDB by piping JSON to stdin:
   echo '{{"questions":[{{"q":"...","choices":["A)...","B)...","C)...","D)..."],"answer":"B"}},...]}}'  | {VENV_PYTHON} {SCRIPT_DIR}/quiz_save.py
   The JSON must have a "questions" array where each item has "q", "choices", and "answer" fields.
   Multiple quizzes per day are allowed — each save creates a new document, never overwrites.
   Return the full list of questions and answers in the agent result.
5. When the background agent completes, present ALL 5 questions at once in a numbered list.
   Always include today's date in the title, e.g.: "## Daily Quiz - 2026-03-30"
   This prevents confusion with leftover quizzes from earlier in a long session.
   Use compact one-line format for choices, e.g.:
   **1.** Question text?
   A) Option 1 · B) Option 2 · C) Option 3 · D) Option 4
6. Wait for the user to answer.
   When showing an example answer format, use a generic pattern like "A B C D A".
   NEVER construct the example from the actual answer key — it leaks the correct answers.
7. Grade by piping the user's answers as JSON to stdin:
   echo '{{"quiz_id": "<_id from the saved quiz>", "answers": ["B", "C", "A", ...]}}' | {VENV_PYTHON} {SCRIPT_DIR}/quiz_grade.py
   This grades the quiz, saves the score to MongoDB, and marks the quiz as complete — all in one step.
   The script returns JSON with score, total, and per-question results (including the full question text, all choices, the user's answer, and the correct answer).
   Show the user their score. For EVERY wrong answer, render the original question with all four choices verbatim (using the `choices` array from the result), mark the user's pick and the correct pick, then explain why the correct one is right. Don't summarize the question or drop the choice text — the user wants to see exactly what they got asked.

ONLY dismiss the quiz if the user EXPLICITLY says one of these exact phrases: "skip quiz", "no quiz today", or "dismiss quiz".
Do NOT dismiss based on indirect hints, casual remarks, or anything ambiguous. If unsure, ask the user directly: "Would you like to skip today's quiz?"
To dismiss, run:
   {VENV_PYTHON} {SCRIPT_DIR}/quiz_dismiss.py
This dismisses the quiz for today.

Keep it quick and fun."""

instructions_file = SCRIPT_DIR / 'quiz-instructions-active.txt'
instructions_file.write_text(instructions, encoding='utf-8')

# Short reason for user-visible feedback, full details in file for Claude
reason = f"Daily quiz pending. Read {instructions_file} and follow the instructions."
print(json.dumps({"decision": "block", "reason": reason}))
