-- claude.ai chat-history archive — Postgres (Neon) schema, phase 1 (full-text).
--
-- Mirrors the youtube-map-api conventions: snake_case, bigint identity PKs,
-- timestamptz created_at/updated_at, natural text UNIQUE keys, explicit indexes.
-- Phase 2 (semantic search) adds `CREATE EXTENSION vector` + an embedding column
-- in a separate migration — intentionally NOT here, so phase 1 needs only stock
-- Postgres full-text.
--
-- Apply:  psql "$DATABASE_URL" -f schema.sql
--    or:  python claude_history.py init-db

CREATE TABLE IF NOT EXISTS conversations (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conv_uuid     text NOT NULL UNIQUE,
    title         text,
    created_at    timestamptz,
    updated_at    timestamptz,
    message_count integer NOT NULL DEFAULT 0,
    imported_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS messages (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    msg_uuid    text UNIQUE,
    conv_uuid   text NOT NULL REFERENCES conversations(conv_uuid) ON DELETE CASCADE,
    seq         integer,                 -- order within the conversation
    role        text,                    -- 'human' | 'assistant' | other
    body        text,                    -- extracted plain text
    created_at  timestamptz,
    -- Full-text vector, auto-maintained. 'simple' config (no stemming) is the
    -- safe default for mixed KO/EN chats; semantic search (phase 2) covers the
    -- fuzzy / cross-lingual "I only remember the gist" cases.
    body_tsv    tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(body, ''))) STORED,
    imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_messages_conv     ON messages (conv_uuid);
CREATE INDEX IF NOT EXISTS idx_messages_created  ON messages (created_at);
CREATE INDEX IF NOT EXISTS idx_messages_tsv      ON messages USING gin (body_tsv);
CREATE INDEX IF NOT EXISTS idx_conversations_upd ON conversations (updated_at);
